############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3


# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
